### ISSUE TITLE
Support for 0.12.0

### ISSUE THREAD

**Issue by roelj** [detrout/debian-guix#1]
Hello there,

First of all, thanks for the code and instructions!  This is pretty cool.
Secondly, I'd like to make a Debian package for the latest (0.12.0) release, but upon building, 92 tests fail.

Do you have time to help me look into this?

Thanks!
~ Roel

**Comment by detrout** [comment]
I did update the packaging. (it took me two tries)

Though I'm seeing the unit test fails too, not sure why
